# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::index

app_invitations:
    path: /invitaciones
    controller: App\Controller\InvitationsController::index

app_blocked:
    path: /bloqueados
    controller: App\Controller\BlockedController::index

app_nearby_users:
    path: /usuarios-cercanos
    controller: App\Controller\NearbyUsersController::index
